### ISSUE TITLE
What is the right way to build this project and use the html3pdf.js file?

### ISSUE THREAD

**Issue by Arcticn** [davidnbooth/html3pdf.js#5]
Hi @davidnbooth and @wattsk90,
Firstly, I want to thank you for maintaining this great project, it fixes the problem in html2pdf.

Recently, @wattsk90 pull a request and I found it useful in speeding up the pdf generation. 
I tried to build this project with  "dev": "webpack --env=dev", and I got the "html3pdf.js" and “html3pdf.bundle.js”.

My question is, how can I import that thing into a project (like a Typescript project) ?
I tried using `import html2pdf from './html3pdf.js'`, but there seems no html2pdf module in "html3pdf.js", and the compiler tells me `"html2pdf" is not exported by "./html3pdf.bundle.js"`. But I checked the source code of this project and I found `export default html2pdf;`.

I am a freshman in javascript and I'm confused about that, what is the right way to build and use it?
Thanks for your help!

**Comment by wattsk90** [comment]
Hi @Arcticn,

I used import `html3pdf` for this package. For me, I used `patch-package` to use the changes I made until a new release including these changes is available.

High-level steps include.

1. Build `html3pdf`
2. Copy files to `node_modules` in the project you wish to use it in.
3. Run `patch-package`

**Comment by davidnbooth** [comment]
Hi @wattsk90 and @Arcticn, I merged the PR so this should be easier now.

Thanks @wattsk90!

**Comment by Arcticn** [comment]
Thanks @wattsk90 and @davidnbooth !
Really learned a lot : )
